#!/bin/bash

zenity --question --width=320 --height=240 --text="Esta aplicación instalará configuraciones pensadas SOLAMENTE para las netbooks del Programa Conectar Igualdad. Si esta computadora no es el programa, se podrían perder datos o algunos programas podrían dejar de funcionar. ¿Desea continuar con la instalación?"

if [ $? = 1 ]; then
        zenity --info --width=320 --height=240 --text "Instalación cancelada." 
        exit 1
else
        exit 0
fi