#!/bin/bash

if [ ! -e /media/DATOS ]; then
        echo "La partición DATOS no existe o no está montada"
        exit 0
fi

if [ ! -e "/media/DATOS/Mis Cosas" ]; then
		mkdir "/media/DATOS/Mis Cosas" 
        echo "Creando carpeta Mis Cosas"
fi

for i in Descargas Música Documentos Imágenes Videos Vídeos; do
	case $i in
		Descargas) 
			if [ -e /home/alumno/$i ]; then
				echo "Moviendo carpeta $i"
				if [ -e "/media/DATOS/Mis Cosas/Descargas" ]; then
					mv -f /home/alumno/$i/* "/media/DATOS/Mis Cosas/Descargas/"
					rm -R /home/alumno/$i
				else
					mv -f /home/alumno/$i "/media/DATOS/Mis Cosas/Descargas"
				fi;             
        	fi;
		;;
		Música)
			if [ -e /home/alumno/$i ]; then
                echo "Moviendo carpeta $i"
				if [ -e "/media/DATOS/Mis Cosas/Mi música" ]; then
					mv -f /home/alumno/$i/* "/media/DATOS/Mis Cosas/Mi música/"
					rm -R /home/alumno/$i
				else
					mv -f /home/alumno/$i "/media/DATOS/Mis Cosas/Mi música"
				fi; 
        	fi;
		;;
		Documentos)
			if [ -e /home/alumno/$i ]; then
                echo "Moviendo carpeta $i"
				if [ -e "/media/DATOS/Mis Cosas/Mis documentos" ]; then
					mv -f /home/alumno/$i/* "/media/DATOS/Mis Cosas/Mis documentos/"
					rm -R /home/alumno/$i
				else
					mv -f /home/alumno/$i "/media/DATOS/Mis Cosas/Mis documentos"
				fi;
        	fi;
		;;
		Imágenes)
			if [ -e /home/alumno/$i ]; then
                echo "Moviendo carpeta $i"
				if [ -e "/media/DATOS/Mis Cosas/Mis imágenes" ]; then
					mv -f /home/alumno/$i/* "/media/DATOS/Mis Cosas/Mis imágenes/"
					rm -R /home/alumno/$i
				else
					mv -f /home/alumno/$i "/media/DATOS/Mis Cosas/Mis imágenes"
				fi;
        	fi;
		;;
		Videos)
			if [ -e /home/alumno/$i ]; then
                echo "Moviendo carpeta $i"
				if [ -e "/media/DATOS/Mis Cosas/Mis vídeos" ]; then
					mv -f /home/alumno/$i/* "/media/DATOS/Mis Cosas/Mis vídeos/"
					rm -R /home/alumno/$i
				else
					mv -f /home/alumno/$i "/media/DATOS/Mis Cosas/Mis vídeos"
				fi;
        	fi;
		;;
		Vídeos)
			if [ -e /home/alumno/$i ]; then
                echo "Moviendo carpeta $i"
				if [ -e "/media/DATOS/Mis Cosas/Mis vídeos" ]; then
					mv -f /home/alumno/$i/* "/media/DATOS/Mis Cosas/Mis vídeos/"
					rm -R /home/alumno/$i
				else
					mv -f /home/alumno/$i "/media/DATOS/Mis Cosas/Mis vídeos"
				fi;
        	fi;
		;;
	  esac
done

ln -s "/media/DATOS/Mis Cosas/Descargas/" /home/alumno/Descargas
ln -s "/media/DATOS/Mis Cosas/Mi música/" /home/alumno/Música
ln -s "/media/DATOS/Mis Cosas/Mis documentos/" /home/alumno/Documentos
ln -s "/media/DATOS/Mis Cosas/Mis imágenes/" /home/alumno/Imágenes
ln -s "/media/DATOS/Mis Cosas/Mis vídeos/" /home/alumno/Videos
chown -R alumno:alumno /home/alumno/Descargas /home/alumno/Música /home/alumno/Documentos /home/alumno/Imágenes /home/alumno/Videos

echo "Symlinks creados en la carpeta Home del alumno"
